### ISSUE TITLE
Lack of CWV events in the RUM data

### ISSUE THREAD

**Issue by ekremney** [adobe/helix-rum-enhancer#121]
## Overview
Currently, there is a lack of CWV events in the RUM data, making the CWV in RUM unusable for sites with lower pageviews. The table below displays the counts of unique RUM events received for `https://blog.adobe.com/`.

| checkpoint[value] | count |
|-------------------|-------|
| top               | 729   |
| lazy              | 699   |
| cwv[TTFB]         | 455   |
| cwv[LCP]          | 125   |
| cwv[CLS]          | 122   |
| cwv[INP]          | 76    |
| cwv[FID]          | 67    |

Ideally, we would expect to see as many LCP events as `lazy` because the `rum-enhancer` is loaded during the lazy phase. However, the way the `GoogleChrome/web-vitals` library works is that it reports LCP, CLS, and INP events when the user interacts (clicks, scrolls, etc.) or leaves the page. This is because LCP might change during the life of the page and must not be reported eagerly, see: https://web.dev/articles/lcp#when-is-lcp-reported

## Proposed Actions
The `GoogleChrome/web-vitals` library provides an option called `reportAllChanges` to report the CWV events as changes occur. However, it is not recommended for production use since the LCP candidate for webpages often changes, and the first candidate may not always be correct, see: https://github.com/GoogleChrome/web-vitals?tab=readme-ov-file#report-the-value-on-every-change

On the other hand, `aem-boilerplate` loads the LCP block eagerly, and the `rum-enhancer` loads at the end of the lazy phase when not only the LCP block but also all blocks are already loaded. There is a very high chance that the LCP is established at the end of lazy phase. Therefore, it should be safe to take the first LCP candidate if the `GoogleChrome/web-vitals` library is loaded at the end of the lazy.

There seems to be two concerns:
1. There is again a possibility (I don't know how big or small) that we could have more than one LCP reported per unique ID in RUM. Therefore, we must check if we need to adjust the queries that calculate the CWV in helix-run-query if we want to go this way.

2. AEM-CS projects do not use `aem-boilerplate` so, it is very likely that this solution will generate multiple entries per unique ids

There is a very good explanation about this by one of the original authors of the library: https://github.com/GoogleChrome/web-vitals/issues/405#issuecomment-1839714899

**Comment by trieloff** [comment]
I don't think that this is a real issue as low traffic sites also are low value targets for performance optimization.

If you want to try this in a project, I suggest to create a PR there that inlines the rum-enhancer with the changes you are suggesting, and then we look at the data to see how much this increases the data footprint and how much noise it introduces.

**Comment by ekremney** [comment]
@trieloff I think this is a real issue. Please check the table above. For a URL which has 72900 pageviews, we only have 125 CWV events which contain LCP. 

125 datapoints is not enough to say anything about LCP value of a url. This tool says we need at least 383 datapoints to predict the average value of a population within 95% confidence level.

![Screenshot 2024-02-26 at 16 33 42](https://github.com/adobe/helix-rum-enhancer/assets/1171225/45b887db-6b16-4fc7-8a57-8a1629fea8f0)

If we had as many LCP events as `lazy` then this wouldn't be an issue
