### ISSUE TITLE
Icon should not be tracked

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-rum-enhancer#203]
With https://github.com/adobe/helix-rum-enhancer/pull/196, the `picture > img` selector has been replaced with `img`. For Helix sites, this means will start tracking icons as soon as a site uses `enhancer@v2`. This is where we should start having different code for Helix sites vs "CQ" site vs generic site for tracking.

cc @trieloff

**Comment by trieloff** [comment]
@davidnuescheler always complained that the icon was not tracked. "The icon should be the most popular image on every site".
So I agree on the sentiment, but don't like the idea of different code bases yet.
