### ISSUE TITLE
viewmedia checkpoint missing for images added "later"

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-rum-enhancer#225]
When a block adds images slightly "later" in the loading sequence, the `viewmedia` checkpoint is not triggered for those. It is currently the responsibility of the developer to think about "observing" them. 
This requires education of developers and there might be ways to automate this (DOM MutationObserver ?).

This needs to be evaluated carefully, especially on the performance side.

**Comment by igor-grubic** [comment]
Adding the workshop (rushed) PR as it might be useful for illustrational purposes
https://github.com/adobe/helix-rum-enhancer/pull/212/files
