### ISSUE TITLE
Introduce leave checkpoint

### ISSUE THREAD

**Issue by chicharr** [adobe/helix-rum-enhancer#67]
**Is your feature request related to a problem? Please describe.**
Currently we know when users are loading the page but not when they are leaving it

**Describe the solution you'd like**
Listen to `pagehide` and `visibilitychange` events to know when users are leaving a page.

**Describe alternatives you've considered**
Use of other events such as `unload` or `beforeunload` are not recommended

**Comment by bosschaert** [comment]
PR #68 is merged, so is this issue done?
